# Generated by Django 4.2 on 2023-06-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elctronic_Commerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
    ]
