# Generated by Django 4.2 on 2023-06-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elctronic_Commerce', '0005_device_briefdescription_alter_device_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
